#!/usr/bin/env bash
# EKC Global Install — Copy skills/ to ~/.kimi/skills/
# Usage: ./install-global.sh [-f|--force] [-n|--dry-run] [-q|--quiet]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SOURCE="${REPO_ROOT}/skills"
TARGET="${HOME}/.kimi/skills"
STAMP_FILE="${TARGET}/.ekc-installed"

FORCE=0
DRYRUN=0
QUIET=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    -f|--force) FORCE=1; shift ;;
    -n|--dry-run) DRYRUN=1; shift ;;
    -q|--quiet) QUIET=1; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

info()  { [[ $QUIET -eq 0 ]] && echo "$*"; }
ok()    { [[ $QUIET -eq 0 ]] && echo "  [OK] $*"; }
warn()  { echo "  [WARN] $*" >&2; }

if [[ ! -d "$SOURCE" ]]; then
  echo "ERROR: Source directory not found: $SOURCE" >&2
  exit 1
fi

if [[ -d "$TARGET" && ! -f "$STAMP_FILE" ]]; then
  echo "  [ERROR] Refusing to install: ${TARGET} exists but has no EKC stamp." >&2
  echo "  This directory appears to contain user-managed skills." >&2
  echo "  To install EKC globally, either:" >&2
  echo "    1. Remove or backup ~/.kimi/skills/ manually, then re-run." >&2
  echo "    2. If this is an old EKC install without stamp, remove and re-install." >&2
  exit 1
fi

mkdir -p "$TARGET"

if [[ $DRYRUN -eq 1 ]]; then
  info "[DRY-RUN] Mode enabled. No files will be copied."
fi

COPIED=0
UPDATED=0
SKIPPED=0

for skill_dir in "$SOURCE"/*/; do
  [[ -d "$skill_dir" ]] || continue
  skill_name="$(basename "$skill_dir")"
  skill_dest="${TARGET}/${skill_name}"
  skill_md="${skill_dir}/SKILL.md"

  if [[ ! -f "$skill_md" ]]; then
    warn "Skipping '${skill_name}': no SKILL.md found"
    continue
  fi

  action=""
  if [[ ! -d "$skill_dest" ]]; then
    action="copy"
  elif [[ $FORCE -eq 1 ]]; then
    action="overwrite"
  else
    ((SKIPPED++)) || true
    continue
  fi

  if [[ $DRYRUN -eq 1 ]]; then
    info "[DRY-RUN] Would ${action}: ${skill_name}"
    if [[ "$action" == "copy" ]]; then ((COPIED++)) || true; else ((UPDATED++)) || true; fi
    continue
  fi

  if [[ "$action" == "overwrite" ]]; then
    rm -rf "$skill_dest"
  fi

  cp -r "$skill_dir" "$skill_dest"
  if [[ "$action" == "copy" ]]; then ((COPIED++)) || true; else ((UPDATED++)) || true; fi
  ok "$action $skill_name"
done

if [[ $DRYRUN -eq 0 ]]; then
  git_hash="unknown"
  if command -v git >/dev/null 2>&1; then
    git_hash="$(cd "$REPO_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
  fi
  total=$((COPIED + UPDATED + SKIPPED))
  cat > "$STAMP_FILE" <<EOF
# EKC Global Install Stamp
# Generated by: scripts/install-global.sh
# Source: ${SOURCE}
# Timestamp: $(date -Iseconds)
# Git Commit: ${git_hash}
# Total Skills: ${total}
# DO NOT EDIT MANUALLY
EOF
  ok "Stamp file created"
fi

info ""
info "EKC Global Install"
info "=================="
info "Source:  ${SOURCE}"
info "Target:  ${TARGET}"
info ""
info "Copied:   ${COPIED}"
info "Updated:  ${UPDATED}"
info "Skipped:  ${SKIPPED}"
info ""

if [[ -d "$TARGET" ]]; then
  info "Flow skills installed:"
  for flow_dir in "$TARGET"/*/; do
    [[ -d "$flow_dir" ]] || continue
    flow_name="$(basename "$flow_dir")"
    flow_md="${flow_dir}/SKILL.md"
    if [[ -f "$flow_md" ]] && grep -q 'type:\s*flow' "$flow_md" 2>/dev/null; then
      info "  /flow:${flow_name}"
    fi
  done
fi

info ""
if [[ $DRYRUN -eq 1 ]]; then
  info "[DRY-RUN] No files were copied."
else
  info "Next step: Open VS Code or run 'kimi' and type '/flow' to verify."
fi
