# EKC Global Install - Copy skills/ to ~/.kimi/skills/
# Usage: .\install-global.ps1 [-Force] [-DryRun] [-Quiet]

[CmdletBinding()]
param(
    [switch]$Force,
    [switch]$DryRun,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path "$ScriptDir\.." | Select-Object -ExpandProperty Path
$Source = Join-Path $RepoRoot "skills"
$Target = Join-Path $HOME ".kimi/skills"
$StampFile = Join-Path $Target ".ekc-installed"

function Write-Info($msg) { if (-not $Quiet) { Write-Host $msg } }
function Write-Ok($msg) { if (-not $Quiet) { Write-Host "  [OK] $msg" -ForegroundColor Green } }
function Write-Warn($msg) { Write-Warning $msg }

if (-not (Test-Path $Source)) {
    Write-Error "Source directory not found: $Source"
    exit 1
}

if (Test-Path $Target) {
    if (-not (Test-Path $StampFile)) {
        Write-Host "  [ERROR] Refusing to install: $Target exists but has no EKC stamp." -ForegroundColor Red
        Write-Host "  This directory appears to contain user-managed skills." -ForegroundColor Red
        Write-Host "  To install EKC globally, either:" -ForegroundColor Red
        Write-Host "    1. Remove or backup ~/.kimi/skills/ manually, then re-run." -ForegroundColor Red
        Write-Host "    2. If this is an old EKC install without stamp, remove and re-install." -ForegroundColor Red
        exit 1
    }
}

$TargetParent = Split-Path -Parent $Target
if (-not (Test-Path $TargetParent)) {
    if ($DryRun) {
        Write-Info "[DRY-RUN] Would create: $TargetParent"
    } else {
        New-Item -ItemType Directory -Path $TargetParent -Force | Out-Null
    }
}

if ($DryRun) {
    Write-Info "[DRY-RUN] Mode enabled. No files will be copied."
}

$Copied = 0
$Updated = 0
$Skipped = 0
$SourceSkills = Get-ChildItem -Path $Source -Directory | Sort-Object Name

foreach ($SkillDir in $SourceSkills) {
    $SkillName = $SkillDir.Name
    $SkillSource = $SkillDir.FullName
    $SkillDest = Join-Path $Target $SkillName
    $SkillMdSource = Join-Path $SkillSource "SKILL.md"

    if (-not (Test-Path $SkillMdSource)) {
        Write-Warn "Skipping '$SkillName': no SKILL.md found"
        continue
    }

    $Exists = Test-Path $SkillDest
    $ShouldCopy = $false
    $Action = ""

    if (-not $Exists) {
        $ShouldCopy = $true
        $Action = "copy"
    } elseif ($Force) {
        $ShouldCopy = $true
        $Action = "overwrite"
    } else {
        $Skipped++
        continue
    }

    if ($DryRun) {
        Write-Info "[DRY-RUN] Would ${Action}: $SkillName"
        if ($Action -eq "copy") { $Copied++ } else { $Updated++ }
        continue
    }

    if ($Action -eq "overwrite") {
        Remove-Item -Path $SkillDest -Recurse -Force
    }

    Copy-Item -Path $SkillSource -Destination $SkillDest -Recurse -Force
    if ($Action -eq "copy") { $Copied++ } else { $Updated++ }
    Write-Ok "$Action $SkillName"
}

if (-not $DryRun) {
    $GitHash = "unknown"
    try {
        $GitHash = (git -C $RepoRoot rev-parse --short HEAD 2>$null) | Out-String
        $GitHash = $GitHash.Trim()
    } catch { }
    $StampContent = @(
        "# EKC Global Install Stamp"
        "# Generated by: scripts/install-global.ps1"
        "# Source: $Source"
        "# Timestamp: $(Get-Date -Format o)"
        "# Git Commit: $GitHash"
        "# Total Skills: $($Copied + $Updated + $Skipped)"
        "# DO NOT EDIT MANUALLY"
    ) -join "`n"
    Set-Content -Path $StampFile -Value $StampContent -Encoding utf8 -NoNewline
    Write-Ok "Stamp file created"
}

Write-Info ""
Write-Info "EKC Global Install"
Write-Info "=================="
Write-Info "Source:  $Source"
Write-Info "Target:  $Target"
Write-Info ""
Write-Info "Copied:   $Copied"
Write-Info "Updated:  $Updated"
Write-Info "Skipped:  $Skipped"
Write-Info ""

$FlowSkills = @()
if (Test-Path $Target) {
    $FlowSkills = Get-ChildItem -Path $Target -Directory | Where-Object {
        $md = Join-Path $_.FullName "SKILL.md"
        if (Test-Path $md) {
            $c = Get-Content -Path $md -Raw
            $c -match "type:\s*flow"
        } else { $false }
    } | Select-Object -ExpandProperty Name
}

if ($FlowSkills.Count -gt 0) {
    Write-Info "Flow skills installed:"
    foreach ($f in $FlowSkills) {
        Write-Info "  /flow:$f"
    }
}

Write-Info ""
if ($DryRun) {
    Write-Info "[DRY-RUN] No files were copied."
} else {
    Write-Info "Next step: Open VS Code or run 'kimi' and type '/flow' to verify."
}
